#!/bin/bash
echo "🔧 Select deployment method:"
echo "1. EC2"
echo "2. Fargate"
read -p "Enter choice (1 or 2): " choice

if [[ "$choice" == "1" ]]; then
  cd ec2_deployment
  chmod +x launch_ec2_pipeline_instance.sh
  ./launch_ec2_pipeline_instance.sh
elif [[ "$choice" == "2" ]]; then
  cd fargate_deployment
  chmod +x deploy_fargate.sh
  ./deploy_fargate.sh
else
  echo "❌ Invalid choice. Exiting."
  exit 1
fi
